name: Build DSD-FME
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Cygwin and tools
        uses: cygwin/cygwin-install-action@v5
        with:
          packages: gcc-g++, make, git, libfftw3-devel, libsndfile-devel, libusb1.0-devel, libportaudio-devel, librtlsdr-devel
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: audio_work
      - name: Checkout mbelib
        uses: actions/checkout@v4
        with:
          repository: szechyjs/mbelib
          path: mbelib
      - name: Build mbelib
        shell: C:\cygwin\bin\bash.exe --login -o pipefail -e {0}
        run: |
          cd "/cygdrive/d/a/dsd-fme/dsd-fme/mbelib"
          gcc -c *.c
          ar rcs libmbe.a *.o
      - name: Build DSD-FME
        shell: C:\cygwin\bin\bash.exe --login -o pipefail -e {0}
        run: |
          cd "/cygdrive/d/a/dsd-fme/dsd-fme"
          cp mbelib/mbelib.h include/
          cp mbelib/libmbe.a ./
          gcc -O2 -I./include src/*.c -o dsd-fme-aw.exe -L./ -lpthread -lm -lfftw3f -lsndfile -lrtlsdr -lusb-1.0 -lportaudio -lmbe
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: dsd-fme-windows-binary
          path: dsd-fme-aw.exe
